project_id = "wahdjskwegycbrxiyjjg"

[functions.generate-image]
verify_jwt = false

[functions.maintenance]
verify_jwt = false

[functions.send-magic-link]
verify_jwt = false

[functions.cleanup-old-images]
verify_jwt = false
